version: '3.8'

services:
    nestjs:
        #image: imageUrl
        container_name: nestjs
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DB_HOST=${DB_HOST:-localhost}
            - DB_PORT=${DB_PORT:-3306}
            - DB_NAME=${DB_NAME:-DB}
            - APP_PORT=${APP_PORT:-3000}
            - DB_USER=${DB_USER:-root}
            - DB_PASS=${DB_PASS:-password}
            - ENV_TYPE=${ENV_TYPE:-dev}
        volumes:
            - .:/app
        ports:
            - "${APP_PORT:-3000}:${APP_PORT:-3000}"
            - 9229:9229
        depends_on:
            - db

    db:
        image: mysql:8
        container_name: db
        restart: unless-stopped
        ports:
          - "3007:3306"
        environment:
          TZ: Europe/Rome
          MYSQL_ROOT_HOST: "%"
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: ${DB_NAME:-DB}